package Controller;

import DAO.AccelerationDAO;
import Model.Acceleration;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

/**
 * Created by cknev on 12-1-2018.
 */

@Controller
@RequestMapping("/accelerations")
public class AccelerationController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccelerationDAO accelerationDAO;

    @PostMapping(path = "/add") // POST request enabled
    public @ResponseBody
    String addNewAcceleration (@RequestBody Acceleration acceleration) {
        try {
            accelerationDAO.save(acceleration);
            return "{saved:true}";
        }
        catch (Exception e){ //When an error occurs, the error will be returned as a message in the json response
            return "{saved:false, error:" + e + "}";
        }
    }

    @RequestMapping(path = "delete/all") // GET request enabled
    public @ResponseBody
    String deleteAllAccelerations (){
        long count = accelerationDAO.count();
        accelerationDAO.deleteAll();
        return "All " + count + "are deleted succesfully";
    }
    @RequestMapping(path = "last") // GET request enabled
    public @ResponseBody
    Acceleration getLastAcceleration (){
       return accelerationDAO.findFirstByOrderByIdDesc();
    }
}
