package Controller;

import DAO.FriendDAO;
import Model.Friend;
import Model.Location;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * Created by cknev on 12-1-2018.
 */

@Controller
@RequestMapping(path = "/friend")
public class FriendController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FriendDAO friendDAO;

    @PostMapping(path = "/add") // POST request enabled
    public @ResponseBody
    String addNewFriend(@RequestBody Friend friend) {
        friendDAO.save(friend);
        return "Saved";
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Friend> getAllFriends() {
        // This returns a JSON list with all the users.
        return friendDAO.findAll();

    }



    @GetMapping(path = "/test")
    public @ResponseBody
    String testMethod() {
        return "Succes";
    }

}
