package Controller;

import DAO.FriendDAO;
import Model.Friend;
import Model.Location;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * @author chrisneven
 * The FriendController class is responsible for handeling requests by using the DAO's for saving and the model for defining objects that are received.
 * from the frontend. The Controller is the bridge between mobile application and the DAO -> database.
 */

@Controller
@RequestMapping(path = "/friend")
public class FriendController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FriendDAO friendDAO;

    /**
     * Method for capturing friend objects and giving it to the FriendDAO wich adds it to the db
     * @param friend
     * @return A string in JSON format so the mobile application can handle it properly
     */
    @PostMapping(path = "/add") // POST request enabled
    public @ResponseBody
    String addNewFriend(@RequestBody Friend friend) {
        friendDAO.save(friend);
        return "Saved";
    }

    /**
     * Method for handling the request which gets all the friend objects from the database
     * @return Friend Iterable of all the friends in the database
     */
    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Friend> getAllFriends() {
        // This returns a JSON list with all the friends.
        return friendDAO.findAll();

    }


    /**
     * Dummy method for testing the API
     * @return String
     */
    @GetMapping(path = "/test")
    public @ResponseBody
    String testMethod() {
        return "Succes";
    }

}
