package Controller;

import DAO.InfoDAO;
import Model.CPUTemp;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Created by cknev on 12-1-2018.
 */

@Controller
@RequestMapping("/info")
public class InfoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private InfoDAO infoDAO;

    @PostMapping(path = "/cputemp/add") // POST request enabled
    public @ResponseBody
    String addNewCPUTemp (@RequestBody CPUTemp cpuTemp) {
        try {
            infoDAO.save(cpuTemp);
            return "{saved:true}";
        }
        catch (Exception e){ //When an error occurs, the error will be returned as a message in the json response
            return "{saved:false, error:" + e + "}";
        }
    }

}
