package Controller;

import DAO.UserDAO;
import Model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * Created by cknev on 12-1-2018.
 */

@Controller
@RequestMapping(path="/user")
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserDAO userDAO;

    @PostMapping(path = "/add") // POST request enabled
    public @ResponseBody
    String addNewUser (@RequestBody User user) {
        userDAO.save(user);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON list with all the users.
        return userDAO.findAll();

    }
    @GetMapping(path="/test")
    public @ResponseBody String testMethod(){
        return "Succes";
    }
}
